<x-app>
<section class="w-full md:w-2/3 flex flex-col items-center px-3">

            <article class="flex flex-col shadow my-4">
           
                
                <div class="bg-white flex flex-col justify-start p-6 font-mono">
                    <a href="#" class="text-green-700 text-sm font-bold uppercase pb-4">Terms</a>
                    <a href="#" class="text-3xl font-bold hover:text-gray-700 pb-4">Privacy Policy</a>
                    <p href="#" class="text-sm pb-8">
                        By <a href="#" class="font-semibold hover:text-gray-800">Alisher Yegizov</a>, WEB PROJECT 2021
                    </p>
                    <h1 class="text-2xl font-bold pb-3">Forum's privacy policy </h1>
                    <p class="pb-3">Forum for the Future (Forum) is committed to protecting your privacy in accordance with our obligations under data protection legislation. The current data protection law is found in the Data Protection Act 1998 but with effect from 25th May 2018, the main data protection law will be the General Data Protection Regulation as supplemented by the Data Protection Act 2018 and related laws.

This privacy policy explains what information Forum collects about you and how it will be used.

Forum promises to respect any personal data you share with us, or that we get from other organisations, and to keep it safe. We aim to be clear when we collect your data and not do anything you wouldn’t reasonably expect.

If you have any queries regarding this privacy policy please contact us at 19-23 Ironmonger Row, London EC1V 3QN, email info@forumforthefuture.org or telephone +44 (0)20 7324 3630</p>
                    <h1 class="text-2xl font-bold pb-3">Main Information</h1>
                    <p class="pb-3">A cookie consists of information sent by a web server to a web browser, and stored by the browser. The information is then sent back to the server each time the browser requests a page from the server. This enables the web server to identify and track the web browser.

Most browsers allow you to reject all cookies, whilst some browsers allow you to reject just third party cookies. Blocking all cookies will, however, have a negative impact upon the usability of many websites, including ours.

We use Google Analytics to analyse the use of this website. Google Analytics generates statistical and other information about website use by means of cookies, which are stored on users' computers. The information generated relating to our website is used to create reports about the use of the website. Google will store this information. For more information about Google’s privacy policy in regards to Google Analytics, please see www.google.com/analytics/learn/privacy.html

The information generated by the cookie about your use of Forum’s websites will be transmitted and stored by Google on servers in the United States.

In addition to reporting website usage statistics, we use Google Analytics in conjunction with additional advertising cookies. We use these cookies to select advertising based on what’s relevant to you, to measure interactions with the ads we display and to improve reporting on campaign performance.</p>
                    <p class="pb-3">Forum will not merge personally identifiable information with anonymous information gathered from these analytics systems unless there is prior notice and affirmative consent via opt-in from the user. When using any of these tracking tools Forum does not identify users or facilitate the merging of personally identifiable information with non-personally identifiable information collected.</p>
                    <p class="pb-3">The personal information we collect might include your name, address, email address, IP address, and information regarding what pages are accessed and when. The type of personal information we will collect about you will depend on the purpose of collecting the information. </p>
                    <h1 class="text-2xl font-bold pb-3">Conclusion</h1>
                    <p class="pb-3">You always have a choice as to whether and how you want to receive communications about our work, products and services and ways you can get involved. If you do not want us to use your contact details to contact you in the future you can opt out of this when we collect your details or at a later time.

If you ever want to change your contact preferences, or opt out of communications, you can do this at any time by updating your preferences via one of our email communications.

Alternatively, you can opt out of our email marketing at any time by clicking the unsubscribe link at the bottom of any email from us. If you choose not to be contacted by us we will never send you personalised marketing communications, but we will keep your details on a ‘suppression list’ to ensure you aren’t contacted.</p>
                </div>
            </article>

            

            <div class="w-full flex flex-col text-center md:text-left md:flex-row shadow bg-white mt-10 mb-10 p-6 font-mono">
                <div class="w-full md:w-1/5 flex justify-center md:justify-start pb-4">
                    <img src="https://source.unsplash.com/collection/1346951/150x150?sig=1" class="rounded-full shadow h-32 w-32">
                </div>
                <div class="flex-1 flex flex-col justify-center md:justify-start">
                    <p class="font-semibold text-2xl">Alisher Yegizov</p>
                    <p class="pt-2">Forum's main admin</p>
                    <div class="flex items-center justify-center md:justify-start text-2xl no-underline text-blue-800 pt-4">
                        <a class="" href="#">
                            <i class="fab fa-facebook"></i>
                        </a>
                        <a class="pl-4" href="#">
                            <i class="fab fa-instagram"></i>
                        </a>
                        <a class="pl-4" href="#">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a class="pl-4" href="#">
                            <i class="fab fa-linkedin"></i>
                        </a>
                    </div>
                </div>
            </div>

        </section>
</x-app>